[package]
name = "xp4_istio_wasme_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
  
[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]


[dependencies]
log = "0.4.17"
proxy-wasm = "0.2.0"
